// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeEDp2urvAuUt7o4j7pufX6MVz6HIyPnE',
    appId: '1:281068618625:web:f666eba55358fb45e71e80',
    messagingSenderId: '281068618625',
    projectId: 'flutterhw-b4b28',
    authDomain: 'flutterhw-b4b28.firebaseapp.com',
    storageBucket: 'flutterhw-b4b28.appspot.com',
    measurementId: 'G-T9SNNZ2CPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnh43zS2-6JuH7x8F8b8hQsXCNK5aPvl0',
    appId: '1:281068618625:android:f837a8d5bb4a6abfe71e80',
    messagingSenderId: '281068618625',
    projectId: 'flutterhw-b4b28',
    storageBucket: 'flutterhw-b4b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ4DSiGIOF4RFRV8Je-xv6XFz2tPDIxSw',
    appId: '1:281068618625:ios:8adc4e96b2a4923ae71e80',
    messagingSenderId: '281068618625',
    projectId: 'flutterhw-b4b28',
    storageBucket: 'flutterhw-b4b28.appspot.com',
    iosBundleId: 'com.example.flutterHw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ4DSiGIOF4RFRV8Je-xv6XFz2tPDIxSw',
    appId: '1:281068618625:ios:8adc4e96b2a4923ae71e80',
    messagingSenderId: '281068618625',
    projectId: 'flutterhw-b4b28',
    storageBucket: 'flutterhw-b4b28.appspot.com',
    iosBundleId: 'com.example.flutterHw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeEDp2urvAuUt7o4j7pufX6MVz6HIyPnE',
    appId: '1:281068618625:web:9c4203d53230d154e71e80',
    messagingSenderId: '281068618625',
    projectId: 'flutterhw-b4b28',
    authDomain: 'flutterhw-b4b28.firebaseapp.com',
    storageBucket: 'flutterhw-b4b28.appspot.com',
    measurementId: 'G-CDVJX87J6N',
  );

}